### PR TITLE
Update raspi build

### PR DESCRIPTION
**Pull request by razr**
here is the summary of changes
* update Ubuntu ```raspi``` kernel to 1034
* do not fail if some patches are skipped
  * It could be that the RT_PATCH is not exactly aligned with the ```raspi``` kernel and some patches are already applied. Let us do not fail if the patch skipped.
* calculate the closest RT patch instead of hardcoding it
  * introduce a shell script that calculates the RT patch closest to the ```raspi`` kernel
* find the latest UNAME_R instead of hardcoding it
  * retrieve the latest ```raspi``` kernel from the list
* use merge_config.sh to merge kernel fragments

### CODE REVIEW

**Review by LanderU — APPROVED** [review]
LGTM! Thanks a lot!

**Review by carlossvg — APPROVED** [review]

**Comment by razr** [comment]
@LanderU could you please approve it again. I have changed review policies and now it will be automatically merged after the second review

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by LanderU** [comment]
@razr you need another approval.

**Comment by LanderU** [comment]
Oh wait! I'm not code owner for this repo.

**Pull request merged**
